import Head from 'next/head';
import Link from "next/link";
import { useEffect } from 'react';

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="home">
        <nav>
        <h1>Next Playground</h1>
          <div className="nav-menu">
            <Link href="/store" className="nav-menu-item">
              <h4>Store</h4>
            </Link>
            <Link href="/reactQuery" className="nav-menu-item">
              <h4>React Query</h4>
            </Link>
            <Link href="/video" className="nav-menu-item">
              <h4>Video Player</h4>
            </Link>
          </div>
        </nav>
      </main>
    </>
  )
}

export default Home;